# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/demo_cpu/demo_cpu.runs/synth_1/processor.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/demo_cpu/demo_cpu.cache/wt [current_project]
set_property parent.project_path D:/demo_cpu/demo_cpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/demo_cpu/demo_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/demo_cpu/demo_cpu.srcs/sources_1/ip/instruction_mem/instructions.coe
add_files {{D:/demo_cpu/demo_cpu.srcs/sources_1/imports/New folder/a.coe}}
add_files D:/demo_cpu/demo_cpu.srcs/sources_1/ip/data_mem/data_mem.coe
read_verilog -library xil_defaultlib {
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/ALU.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/Q2/CLA_16_bit_lookahead.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/Q2/CLA_4_bit_augmented.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/MUX_2to1.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/MUX_4to1.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/new/PIPO_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/add_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/adder_2bit.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/adder_3bit.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/and_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/comparator.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/complement_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/computational_block.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/control_unit.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/decoder_16bit.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/decoder_8bit.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/Q1/full_adder.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/hamm.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/instruction_decoder.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/Q2/look_ahead_unit.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/lui_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/ALU/mux_2_1.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/shift/mux_32_1.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/or_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/new/register_bank.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/ALU/reverse_bits.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/ALU/sar_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/signextend.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/ALU/sll_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/imports/ALU/slr_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/time_step.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/imports/sources_1/new/xor_module.v
  D:/demo_cpu/demo_cpu.srcs/sources_1/new/processor.v
}
read_ip -quiet D:/demo_cpu/demo_cpu.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all d:/demo_cpu/demo_cpu.gen/sources_1/ip/data_mem/data_mem_ooc.xdc]

read_ip -quiet D:/demo_cpu/demo_cpu.srcs/sources_1/ip/instruction_mem/instruction_mem.xci
set_property used_in_implementation false [get_files -all d:/demo_cpu/demo_cpu.gen/sources_1/ip/instruction_mem/instruction_mem_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/demo_cpu/demo_cpu.srcs/constrs_1/new/intrun.xdc
set_property used_in_implementation false [get_files D:/demo_cpu/demo_cpu.srcs/constrs_1/new/intrun.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/demo_cpu/demo_cpu.srcs/utils_1/imports/synth_1/integrate.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top processor -part xc7a100tcsg324-3
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef processor.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file processor_utilization_synth.rpt -pb processor_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
